### ISSUE TITLE
d2 HEAD not compatible 

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-vscode#56] opened 2023-03-03 17:47 UTC
not sure why, but there was a regression in master right now where errors are not being shown. when i pull master and run `go install .`, the following file doesn't report errors when previewing.

![Screen Shot 2023-03-03 at 9 44 22 AM](https://user-images.githubusercontent.com/3120367/222790981-f2737af9-5469-4a0b-9f5b-02a3097d1211.png)

but when I install `d2` from homebrew, it works fine:

![Screen Shot 2023-03-03 at 9 42 57 AM](https://user-images.githubusercontent.com/3120367/222791044-2a9fa997-5b13-4349-91e8-19eec8683776.png)

```
input: |d2
  hello -> world
|

input -> compiler.parse

compiler: {
  parse -> AST
  AST: Abstract Syntax Tree {
    shape: oval
  fill: honeydew
  }

  AST -> compile
}

compiler.compile -> graph
graph: Graph\n(shapes & connections) {
  shape: oval
  fill: honeydew
}

graph -> Set Dimensions
Set Dimensions -> Use ruler to measure all texts -> measured graph
Set Dimensions -> Use given, premeasured dimensions -> measured graph

measured graph: {
  shape: oval
  fill: honeydew
}

measured graph -> layout engine -> positioned graph

positioned graph: {
  shape: oval
  fill: honeydew
}

positioned graph -> exporter -> diagram

diagram: finalized diagram (styled) {
  shape: oval
  fill: honeydew
}

diagram -> render SVG

render SVG -> use sketch post processor: optional

use sketch post processor -> SVG bytes

SVG bytes: {
  shape: oval
  fill: honeydew
}

SVG bytes -> screenshot for PNG: optional
```

for context, there was a regression with errors not being reported on cli at all, but i already fixed that: https://github.com/terrastruct/util-go/commit/56bcfcdf965dba56804a6b2b3b90c473b4a543a6

i wonder if it's something else in util-go changes that could affect this.

the errors are reported exactly the same though so i don't see how it could

![Screen Shot 2023-03-03 at 9 47 10 AM](https://user-images.githubusercontent.com/3120367/222791487-6163d4a1-49a8-46dd-b6f9-8d31c39ebe2e.png)

**Comment by alixander** [comment] 2023-03-03 17:49
cc @nhooyr just in case somethng jumps out

**Comment by nhooyr** [comment] 2023-03-03 17:52
No clue, weird.

**Comment by alixander** [comment] 2023-03-03 18:52
<img width="614" alt="Screen Shot 2023-03-03 at 10 52 43 AM" src="https://user-images.githubusercontent.com/3120367/222803263-98fde4e8-09fa-4aa1-becb-82dee59f34d2.png">

**Comment by alixander** [comment] 2023-03-03 19:02
i'm highly dubious. are you asking because you can't reproduce?

**Comment by gavin-ts** [comment] 2023-03-03 19:16
I can reproduce it now, looks like 09544af0 is what broke it and for some reason 505183aa doesn't fix it

**Comment by nhooyr** [comment] 2023-03-03 19:34
Huh super interesting, so it is something in my PR. I honestly have no clue what it could even be especially after @alixander's fix.

**Comment by gavin-ts** [comment] 2023-03-03 19:48
maybe we need to call `.Close` on stderr elsewhere if we aren't calling it anymore

**Comment by alixander** [comment] 2023-03-03 19:54
it wasn't being called before that change either.

**Comment by gavin-ts** [comment] 2023-03-03 20:15
how does the fix work?
was it closing too early hence the no output from @nhooyr 's change? and is that why [this fix](https://github.com/terrastruct/util-go/commit/56bcfcdf965dba56804a6b2b3b90c473b4a543a6#diff-4e0187b341bdfeb9aede328214f886de2251a416a34e696bb4fe8d6cb49ccdc2L97-L99) has the error message appear?

but maybe it still needs to close at the right time is what I'm thinking

**Comment by nhooyr** [comment] 2023-03-03 20:18
yes it was closing too early before.
but now @alixander is right, it wasn't being called before and shouldn't be now either.

it being closed is only for tests and that's where @alixander moved the call.

**Comment by nhooyr** [comment] 2023-03-03 20:29
Found the bug fixing.

**Comment by nhooyr** [comment] 2023-03-03 20:57
Can confirm https://github.com/terrastruct/d2/pull/969 fixes this. We didn't have a test for stdin to stdout output and I didn't realize I broke it with a few changes in d2cli.

**Closed** 2023-03-03 20:59 UTC

**Comment by alixander** [comment] 2023-03-03 21:15
confirmed as well
