### ISSUE TITLE
in vscode extension on windows, I get 'D2.<command>' not found

### ISSUE THREAD

**Issue by imding** [terrastruct/d2-vscode#74] opened 2023-04-07 15:58 UTC
it happens whenever I try to preview or compile to svg.

**Comment by alixander** [comment] 2023-04-07 16:00
related: https://github.com/terrastruct/d2-vscode/issues/73

**Comment by gavin-ts** [comment] 2023-04-07 18:09
I can't reproduce this issue on my machine, are you able to reproduce this on windows @BarryNolte ?

**Comment by gavin-ts** [comment] 2023-04-07 18:10
@imding if you use vscode menubar `Help`->`Toggle Developer Tools` do you see any error messages in the console?

**Comment by BarryNolte** [comment] 2023-04-07 19:58
@gavin-ts  I'm not seeing anything. I built the vsix based on master and installed it, no obvious problems on Windows or Linux.  I brought up dev tools and didn't see anything there either.  Next bit of troubleshooting is, what extensions are installed (@imding . @quixoticaxis)?

**Comment by quixoticaxis** [comment] 2023-04-07 20:19
I'm using the latest Windows VSCode version (1.77.1).
Dev tools show the following line: `mainThreadExtensionService.ts:112 Activating extension 'Terrastruct.d2' failed: File URL path must be absolute.`

**Comment by gavin-ts** [comment] 2023-04-07 20:35
@BarryNolte I wonder if it is related to the esmoduleinterop change, and if this could fix it: https://github.com/terrastruct/d2-vscode/commit/15d75d66b6c44affbeec8f780cb719fee6ad95a2 . but until we can reproduce the issue we won't be able to confirm the fix. 
I was looking at the changes between master and 57d6782ab37bbcb67ef34f7acf8dfbf6a32bdc4b and this seems like an option

**Comment by BarryNolte** [comment] 2023-04-07 20:53
@gavin-ts This seems to be a likely culprit. The only time I've had extensions fail to load, it's something like an imported module failing to load.

**Comment by gavin-ts** [comment] 2023-04-07 22:17
This looks like a similar issue: https://github.com/microsoft/vscode-go/issues/1386#issuecomment-349220667

**Comment by BarryNolte** [comment] 2023-04-08 01:13
Maybe, but given the bug is 5 years old, I don't know. How about we try the change you made, and if it still works in our machines, at least we know it wasn't made worse.

**Comment by gavin-ts** [comment] 2023-04-08 03:04
ok we can see if it is fixed in 0.8.5

**Comment by quixoticaxis** [comment] 2023-04-08 16:18
@gavin-ts 0.8.5 still does not work the same as 0.8.4 (URL path must be absolute).

**Comment by quixoticaxis** [comment] 2023-04-08 16:34
Extension works on Linux for me, so something is probably OS related.

**Comment by alixander** [comment] 2023-04-08 16:36
did 0.8.4 work on linux for you as well? @quixoticaxis

**Comment by quixoticaxis** [comment] 2023-04-08 16:41
@alixander 0.8.3, 0.8.4, and 0.8.5 work on my Kubuntu (latest stable).
Only 0.8.3 works on my Windows 11 PC.

**Comment by BarryNolte** [comment] 2023-04-08 16:49
It all works on my win10 machine, so win11 related?

**Comment by quixoticaxis** [comment] 2023-04-08 17:08
Disclaimer: I know literally zero javascript.
Debugging the isnstalled extension (running debugger from `%userprofile%\.vscode\extensions\terrastruct.d2-0.8.5` folder) gave me the following callstack:

```
Exception has occurred: TypeError: File URL path must be absolute
t new NodeError (node:internal/errors:371:5)
	at getPathFromURLWin32 (node:internal/url:1390:11)
	at fileURLToPath (node:internal/url:1420:22)
	at 2163 (&userprofile%\.vscode\extensions\terrastruct.d2-0.8.5\dist\extension.js:1:85043)
	at r (&userprofile%\.vscode\extensions\terrastruct.d2-0.8.5\dist\extension.js:1:90391)
	at 6662 (&userprofile%\.vscode\extensions\terrastruct.d2-0.8.5\dist\extension.js:1:51580)
	at r (&userprofile%\.vscode\extensions\terrastruct.d2-0.8.5\dist\extension.js:1:90391)
	at 3961 (&userprofile%\.vscode\extensions\terrastruct.d2-0.8.5\dist\extension.js:1:53416)
	at r (&userprofile%\.vscode\extensions\terrastruct.d2-0.8.5\dist\extension.js:1:90391)
	at 112 (&userprofile%\.vscode\extensions\terrastruct.d2-0.8.5\dist\extension.js:1:54771)
	at r (&userprofile%\.vscode\extensions\terrastruct.d2-0.8.5\dist\extension.js:1:90391)
	at &userprofile%\.vscode\extensions\terrastruct.d2-0.8.5\dist\extension.js:1:90808
	at Object.<anonymous> (&userprofile%\.vscode\extensions\terrastruct.d2-0.8.5\dist\extension.js:1:90833)
	at Module._compile (node:internal/modules/cjs/loader:1165:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at m._load (%letscallitprogramfiles%\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:124:14199)
	at h._load (%letscallitprogramfiles%\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:119:11871)
	at I._load (%letscallitprogramfiles%\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:119:11264)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (%letscallitprogramfiles%\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at E.rb (%letscallitprogramfiles%\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:119:13135)
	at async Promise.all (index 0)
```
Hope it helps.

**Comment by BarryNolte** [comment] 2023-04-08 18:27
Excellent, now I have something to go on! I'll see if my current hunch is correct. Thanks!

**Comment by BarryNolte** [comment] 2023-04-08 19:16
It's the **open** module that I added to open links in the preview window trying get the path to the 'xdg-open' script for **linux**, on a **windows** machine.  This module had a note about not really working in electron apps, so I guess this is the subtle hint to not use it.  Going off to find alternatives...

**Comment by vittee** [comment] 2023-04-09 19:44
The error is originated from this file:
`C:\Users\vittee\.vscode\extensions\terrastruct.d2-0.8.5\dist\extension.js`

And I found that it contains a literal string pointing to an invalid path (on Windows)
```js
const $e = i.dirname((0, s.fileURLToPath)("file:///Users/gavinnishizawa/github_repos/d2-vscode/node_modules/open/index.js"))
```

Simply edit that string to:
```js
const $e = i.dirname((0, s.fileURLToPath)("file://./node_modules/open/index.js"))
```

And it now works

**Comment by vittee** [comment] 2023-04-09 19:52
Might be related to this

https://github.com/sindresorhus/open/blob/accd304abffaec9016f180496d4d3de40145b3c9/index.js#L14

**Comment by therastal** [comment] 2023-04-10 21:43
> The error is originated from this file: `C:\Users\vittee\.vscode\extensions\terrastruct.d2-0.8.5\dist\extension.js`
> 
> And I found that it contains a literal string pointing to an invalid path (on Windows)
> 
> ```js
> const $e = i.dirname((0, s.fileURLToPath)("file:///Users/gavinnishizawa/github_repos/d2-vscode/node_modules/open/index.js"))
> ```
> 
> Simply edit that string to:
> 
> ```js
> const $e = i.dirname((0, s.fileURLToPath)("file://./node_modules/open/index.js"))
> ```
> 
> And it now works

This fixed it for me! 👍

**Comment by Rhywun** [comment] 2023-04-11 14:59
The noted fix worked for me too

**Comment by gavin-ts** [comment] 2023-04-11 20:11
thanks everyone version 0.8.6 is released and should fix this issue

**Comment by alixander** [comment] 2023-04-11 20:42
we'll close this once someone can confirm. @Rhywun @therastal @vittee @quixoticaxis @imding

**Comment by quixoticaxis** [comment] 2023-04-11 20:52
@gavin-ts , @alixander , thank you. 0.8.6 works.

**Closed** 2023-04-11 20:54 UTC

**Comment by alixander** [comment] 2023-04-11 20:56
great. thanks @BarryNolte !

**Comment by jfudickar** [comment] 2023-04-11 22:21
Same for me!
Great work. Thanks

**Comment by imding** [comment] 2023-04-14 02:05
sorry for completely dropping out on the thread.

I only had this issue on windows, will check asap, and thanks so much for fixing it!!

**Comment by imding** [comment] 2023-04-14 13:58
it works!
